fix: Azure does not support suffix range requests (#8685)
Fixes an issue that occurs in distributed query mode (and possibly other
modes) where performing a query on a version controlled Azure blob
conatiner would result in the error:

Error: HTTP 400: Execution error: Job IUniFgx failed: Job failed due to stage 1 failed: Task failed due to runtime execution error: DataFusionError(Execution("DataFusionError(ParquetError(External(NotSupported { source: \"Azure does not support suffix range requests\" })))"))

This commit brings in https://github.com/spiceai/arrow-rs/pull/9 which
provides the file size explicitly which in turn avoids the range
requests.